version: '3'

services:
  logstash:
    volumes:
      - ./logstash/offers-pipeline.conf:/usr/share/logstash/pipeline/offers-pipeline.conf

  leboncoin:
    volumes:
      - ./leboncoin:/usr/src/app/leboncoin

  scheduler:
    volumes:
      - ./:/usr/src/app

  metricbeat:
    volumes:
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d

volumes:
  es_data:
    driver: local
