version: '3'

services:
  logstash:
    volumes:
      - ./logstash:/usr/share/logstash/pipeline/

  leboncoin:
    volumes:
      - ./leboncoin:/usr/src/app/leboncoin

  scheduler:
    volumes:
      - ./:/usr/src/app

  metricbeat:
    volumes:
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d

volumes:
  es_data:
    driver: local
