version: '3'

services:
  nginx:
    image: kphoen/flatrise-nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    environment:
      - USER=test
      - PASSWD=changeme
    depends_on:
      - kibana
    ports:
      - 80:80
    deploy:
      replicas: 1

  elasticsearch:
    image: 'elasticsearch:6.5.1'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          cpus: '0.95'
          memory: 1800M
        reservations:
          cpus: '0.25'
          memory: 1200M

  logstash:
    image: kphoen/flatrise-logstash
    build:
      context: ./logstash
      dockerfile: ./Dockerfile
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m -XX:ParallelGCThreads=1"
    depends_on:
      - rabbitmq
      - elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          cpus: '0.95'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 700M

  kibana:
    image: kphoen/flatrise-kibana
    build:
      context: ./kibana
      dockerfile: ./Dockerfile
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 100M

  rabbitmq:
    image: 'rabbitmq:3.7.8-management'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=flatrise
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

  boligportal:
    image: kphoen/flatrise-boligportal
    build:
      context: .
      dockerfile: ./docker/Dockerfile-boligportal
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq/flatrise
    command: '/docker/wait-for-it.sh -t 60 rabbitmq:5672 -- /app/worker'

  leboncoin:
    image: kphoen/flatrise-leboncoin
    build:
      context: .
      dockerfile: ./leboncoin/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq/flatrise
    command: './docker/wait-for-it.sh -t 60 rabbitmq:5672 -- ./leboncoin/worker.py'

  blocket:
    image: kphoen/flatrise-blocket
    build:
      context: .
      dockerfile: ./docker/Dockerfile-blocket
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq/flatrise
    command: '/docker/wait-for-it.sh -t 60 rabbitmq:5672 -- /app/worker'

  scheduler:
    image: kphoen/flatrise-scheduler
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq/flatrise
    command: './docker/wait-for-it.sh -t 60 rabbitmq:5672 -- ./scheduler/cron.py'

  metricbeat:
    image: kphoen/flatrise-metricbeat
    build:
      context: .
      dockerfile: ./metricbeat/Dockerfile
    command: metricbeat -e -system.hostfs=/hostfs
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
      - rabbitmq
      - logstash
      - kibana
    deploy:
      mode: global

volumes:
  es_data:
    driver: local
