version: '3'

services:
  elasticsearch:
    image: 'elasticsearch:6.5.1'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: 'logstash:6.5.1'
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - rabbitmq
      - elasticsearch
    volumes:
      - ./logstash:/usr/share/logstash/pipeline/

  kibana:
    image: 'kibana:6.5.1'
    ports:
      - 80:5601

  rabbitmq:
    image: 'rabbitmq:3.7.8-management'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=flatrise

  boligportal:
    build:
      context: ./boligportal.dk/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq/flatrise
    command: './docker/wait-for-it.sh -t 60 rabbitmq:5672 -- /app/worker'

  leboncoin:
    build:
      context: .
      dockerfile: ./leboncoin/Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq/flatrise
    command: './docker/wait-for-it.sh -t 60 rabbitmq:5672 -- ./leboncoin/worker.py'

  blocket:
    build:
      context: .
      dockerfile: ./blocket.se/Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq/flatrise
    command: './docker/wait-for-it.sh -t 60 rabbitmq:5672 -- ./blocket.se/worker.py'

  scheduler:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq/flatrise
    command: './docker/wait-for-it.sh -t 60 rabbitmq:5672 -- ./scheduler/cron.py'

  metricbeat:
    build:
      context: .
      dockerfile: ./metricbeat/Dockerfile
    volumes:
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d
    depends_on:
      - elasticsearch
      - rabbitmq
      - logstash

volumes:
  es_data:
    driver: local
