version: '3'

services:
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/entrypoint.sh:/usr/local/bin/entrypoint.sh

  rabbitmq:
    ports:
      - 15672:15672

  kibana:
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    volumes:
      - ./logstash/offers-pipeline.conf:/usr/share/logstash/pipeline/offers-pipeline.conf

  leboncoin:
    volumes:
      - ./leboncoin:/usr/src/app/leboncoin

  scheduler:
    volumes:
      - ./:/usr/src/app

  metricbeat:
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d

volumes:
  es_data:
    driver: local
