logging.level: info

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  index: 'metricbeat-%{+yyyy.MM.dd}'

setup.kibana.host: "kibana:5601"
setup.kibana.protocol: "http"
setup.kibana.path: /kibana

setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true
setup.dashboards.retry.maximum: 10
setup.dashboards.index: 'metricbeat-*'

setup.template:
  name: 'metricbeat'
  pattern: 'metricbeat-*'

metricbeat.config.modules.path: /usr/share/metricbeat/modules.d/*.yml

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~
